= Partenkirchen REST API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3

== signup
=== post
==== 성공
operation::signup/post/success[snippets='curl-request,http-request,http-response']
==== 실패 - username에 공백이 있는 경우
operation::signup/post/fail-with-whitespace-username[snippets='curl-request,http-request,http-response']

== signin
=== get
==== 성공
operation::signin/get/success[snippets='curl-request,http-request,http-response']
==== 실패 - 존재하지 않는 username으로 로그인
operation::signin/get/fail-unexist-username[snippets='curl-request,http-request,http-response']

== user
=== patch
==== 성공
operation::user/patch/success[snippets='curl-request,http-request,http-response']
==== 실패 - 기존 비밀번호가 틀린 경우
operation::user/patch/fail-with-wrong-password[snippets='curl-request,http-request,http-response']
==== 실패 - 새로운 비밀번호 없이 시도
operation::user/patch/fail-without-new-password[snippets='curl-request,http-request,http-response']

=== delete
==== 성공
operation::user/delete/success[snippets='curl-request,http-request,http-response']
==== 실패 - 다른 사람 계정 지우려 하는 경우
operation::user/delete/fail-with-other-account[snippets='curl-request,http-request,http-response']

== project
=== post
==== 성공
operation::projects/post/success[snippets='curl-request,http-request,http-response']
==== 실패 - description 없이 project 생성 시도
operation::projects/post/fail-without-description[snippets='curl-request,http-request,http-response']
=== get all
==== 성공
operation::projects/gets/success[snippets='curl-request,http-request,http-response']
=== get one
==== 성공
operation::projects/get/success[snippets='curl-request,http-request,http-response']
=== patch
==== 성공 - project의 name 변경
operation::projects/patch/success-change-name[snippets='curl-request,http-request,http-response']
==== 성공 - project의 name과 description 변경
operation::projects/patch/success-change-name-and-description[snippets='curl-request,http-request,http-response']
=== delete
==== 성공
operation::projects/delete/success[snippets='curl-request,http-request,http-response']

== issue
=== post
==== 성공
operation::issues/post/success[snippets='curl-request,http-request,http-response']
==== 실패 - priority 없이 issue 생성 시도
operation::issues/post/fail-without-priority[snippets='curl-request,http-request,http-response']
=== get all
==== 성공 - 모든 issue 검색
operation::issues/gets/success[snippets='curl-request,http-request,http-response']
==== 성공 - assignee가 없는 issue 검색
operation::issues/gets/success-with-no-assignee[snippets='curl-request,http-request,http-response']
==== 성공 - title로 검색
operation::issues/gets/success-with-issue-title[snippets='curl-request,http-request,http-response']
==== 성공 - 모든 조건 붙여서 검색
operation::issues/gets/success-combination[snippets='curl-request,http-request,http-response']
=== get one
==== 성공
operation::issues/get/success[snippets='curl-request,http-request,http-response']
=== patch
==== 성공 - assignee 할당
operation::issues/patch/success-change-assignee[snippets='curl-request,http-request,http-response']
==== 성공 - title 변경
operation::issues/patch/success-change-title[snippets='curl-request,http-request,http-response']
==== 성공 - status를 resolved로 변경
operation::issues/patch/success-change-to-resolved[snippets='curl-request,http-request,http-response']
=== delete
==== 성공
operation::issues/delete/success[snippets='curl-request,http-request,http-response']

== comment
=== post
==== 성공 - 해당 issue의 description으로 comment 작성
operation::comments/post/success-as-description[snippets='curl-request,http-request,http-response']
==== 실패 - content 없이 comment 작성
operation::comments/post/fail-without-content[snippets='curl-request,http-request,http-response']
==== 실패 - isDescription 없이 comment 작성
operation::comments/post/fail-without-is-description[snippets='curl-request,http-request,http-response']
=== patch
==== 성공
operation::comments/patch/success[snippets='curl-request,http-request,http-response']
=== delete
==== 성공
operation::comments/delete/success[snippets='curl-request,http-request,http-response']

== permission
=== post
=== get
=== patch
=== delete
