= Partenkirchen REST API Docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3

== signup
=== post
==== 성공
operation::signup/post/success[snippets='curl-request,http-request,http-response']
==== username에 공백이 있는 경우
operation::signup/post/fail-with-whitespace-username[snippets='curl-request,http-request,http-response']

== signin
=== get
==== 성공
operation::signin/get/success[snippets='curl-request,http-request,http-response']
==== 존재하지 않는 username으로 로그인
operation::signin/get/fail-unexist-username[snippets='curl-request,http-request,http-response']

== user
=== patch
==== 성공
operation::user/patch/success[snippets='curl-request,http-request,http-response']
==== 기존 비밀번호가 틀린 경우
operation::user/patch/fail-with-wrong-password[snippets='curl-request,http-request,http-response']
==== 새로운 비밀번호 없이 시도
operation::user/patch/fail-without-new-password[snippets='curl-request,http-request,http-response']

=== delete
==== 성공
operation::user/delete/success[snippets='curl-request,http-request,http-response']
==== 다른 사람 계정 지우려 하는 경우
operation::user/delete/fail-with-other-account[snippets='curl-request,http-request,http-response']
